---
env:
  es2022: true
  node: true
plugins:
  - "sort-class-members"
extends: "eslint:recommended"
globals:
  window: true
rules:
  array-bracket-spacing:
    - 2
    - never
  arrow-parens: 2
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: false
  comma-dangle:
    - 2
    - never
  curly: 2
  eol-last:
    - 2
    - always
  indent:
    - 2
    - 4
    - SwitchCase: 1
      ignoreComments: false
  keyword-spacing:
    - 2
    - after: true
      overrides:
        catch:
          after: false
        for:
          after: false
        if:
          after: false
        switch:
          after: false
        while:
          after: false
  no-prototype-builtins: 0
  no-trailing-spaces: 2
  no-var: 2
  object-curly-spacing:
    - 2
    - never
  object-shorthand:
    - 2
    - consistent-as-needed
  prefer-const: 2
  quotes:
    - 2
    - double
  require-atomic-updates: 1
  semi:
    - 2
    - always
  sort-class-members/sort-class-members:
    - 2
    - order:
      - "[alphabetical-properties]"
      - "[alphabetical-private-properties]"
      - constructor
      - update
      - "[alphabetical-getters]"
      - "[alphabetical-methods]"
      - "[alphabetical-conventional-private-methods]"
      - "[alphabetical-private-methods]"
      - "[everything-else]"
      - "[custom-inspect-method]"
      - toString
      - toJSON
      groups:
        alphabetical-getters:
        - kind: get
          sort: alphabetical
        alphabetical-methods:
        - type: method
          sort: alphabetical
        alphabetical-properties:
        - type: property
          sort: alphabetical
        alphabetical-conventional-private-methods:
        - name: "/_.+/"
          type: method
          sort: alphabetical
        alphabetical-private-methods:
        - type: method
          private: true
          sort: alphabetical
        alphabetical-private-properties:
        - type: property
          private: true
          sort: alphabetical
        custom-inspect-method:
        - name: "[util.inspect.custom]"
          type: method
