name: JavaScript/TypeScript linting
on: [ pull_request ]

jobs:
  lint:
    name: Lint all files
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with: 
          node-version: lts/*
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
      - name: Install dependencies
        # Ignore build scripts as pnpm ignores the optionality of peer dependencies in
        # the root package.json, forcing some of the native dependencies to be installed
        run: pnpm i --no-optional --frozen-lockfile --ignore-scripts 
      - name: Lint all files
        run: pnpm run lint
