name: JavaScript/TypeScript linting
on: [ pull_request ]

jobs:
  lint:
    name: Lint all files
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with: 
          node-version: lts/*
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: pnpm i --omit=optional --frozen-lockfile
      - name: Lint all files
        run: pnpm run lint
