name: JavaScript/TypeScript linting
on: [ pull_request ]

jobs:
  lint:
    name: Lint ${{ matrix.lang.name }} files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lang: 
          - lang: js
            name: JavaScript
          - lang: ts
            name: TypeScript

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: lts/*
      - name: Install dependencies
        run: npm i --omit=optional
      - name: Lint ${{ matrix.lang.name }} files
        run: "npm run lint:${{ matrix.lang.lang }}"
        