name: JavaScript/TypeScript linting
on: [ pull_request ]

jobs:
  lint:
    name: Lint all files
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: lts/*
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i --omit=optional
      - name: Lint all files
        run: "npm run lint"
